// Code generated by protoc-gen-go. DO NOT EDIT.
// source: confarray.proto

package msg

import (
	"bytes"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	"strconv"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ArrayDataBaseConfig struct {
	Data                 []*DataBaseConfig `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ArrayDataBaseConfig) Reset()         { *m = ArrayDataBaseConfig{} }
func (m *ArrayDataBaseConfig) String() string { return proto.CompactTextString(m) }
func (*ArrayDataBaseConfig) ProtoMessage()    {}
func (*ArrayDataBaseConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2657736a5dd0c940, []int{0}
}

func (m *ArrayDataBaseConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrayDataBaseConfig.Unmarshal(m, b)
}
func (m *ArrayDataBaseConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrayDataBaseConfig.Marshal(b, m, deterministic)
}
func (m *ArrayDataBaseConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrayDataBaseConfig.Merge(m, src)
}
func (m *ArrayDataBaseConfig) XXX_Size() int {
	return xxx_messageInfo_ArrayDataBaseConfig.Size(m)
}
func (m *ArrayDataBaseConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrayDataBaseConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ArrayDataBaseConfig proto.InternalMessageInfo

func (m *ArrayDataBaseConfig) GetName() string {
	var buff bytes.Buffer
	buff.WriteString("ArrayDataBaseConfig")
	data := strconv.Quote(buff.String())
	return data
}

func (m *ArrayDataBaseConfig) GetData() []*DataBaseConfig {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ArrayDataBaseConfig)(nil), "msg.ArrayDataBaseConfig")
}

func init() { proto.RegisterFile("confarray.proto", fileDescriptor_2657736a5dd0c940) }

var fileDescriptor_2657736a5dd0c940 = []byte{
	// 103 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xce, 0xcf, 0x4b,
	0x4b, 0x2c, 0x2a, 0x4a, 0xac, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e,
	0x97, 0xe2, 0x01, 0x89, 0x66, 0xa6, 0x43, 0x84, 0x94, 0xec, 0xb8, 0x84, 0x1d, 0x41, 0x2a, 0x5c,
	0x12, 0x4b, 0x12, 0x9d, 0x12, 0x8b, 0x53, 0x9d, 0xc1, 0x92, 0x42, 0xea, 0x5c, 0x2c, 0x29, 0x89,
	0x25, 0x89, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0xc2, 0x7a, 0xb9, 0xc5, 0xe9, 0x7a, 0xa8,
	0x4a, 0x82, 0xc0, 0x0a, 0x92, 0xd8, 0xc0, 0xc6, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xea,
	0x78, 0x0f, 0x3f, 0x6c, 0x00, 0x00, 0x00,
}
